# Autogenerated by devscripts/update-version.py

__version__ = '2025.07.07.1'

RELEASE_GIT_HEAD = '9c5989955cadb6162cb00c2a8daf8750fcceca6f'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'minff/yt-dlp'

ORIGIN = 'minff/yt-dlp'

_pkg_version = '2025.07.07.1'
